openapi: 3.0.3
info:
  description: 画像によるレコメンド機能を添えて
  title: 家具マッチングサービス
  version: 1.0.0
servers:
- description: Local server
  url: http://localhost:8080
tags:
- description: Check API status
  name: OK
- description: ユーザーアカウント管理
  name: User
- description: 家具管理
  name: Furniture
- description: 取引機能
  name: Trade
- description: いいね機能
  name: Favorite
- description: チャット機能
  name: Chat
paths:
  /ok:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OKResponse'
          description: API is running
      summary: Check API status
      tags:
      - OK
  /sign_up:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
        required: true
      responses:
        "200":
          description: User registered successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: sign up
      tags:
      - User
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
          description: User logged in successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: User login
      tags:
      - User
  /logout:
    post:
      responses:
        "200":
          description: User logged out successfully
      summary: User logout
      tags:
      - User
  /furniture:
    get:
      parameters:
      - example: 1
        explode: true
        in: query
        name: user_id
        required: true
        schema:
          type: integer
        style: form
      - description: "カテゴリコード, URL(https://github.com/naka-c1024/Pasha-niture/blob/main/client/app/lib/Domain/constants.dart)"
        explode: true
        in: query
        name: category
        required: false
        schema:
          type: integer
        style: form
      - description: "検索キーワード, スペース区切りで複数指定可"
        example: ソファ かわいい
        explode: true
        in: query
        name: keyword
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FurnitureListResponse'
          description: Furniture list retrieved successfully
      summary: Get list of furniture
      tags:
      - Furniture
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RegisterFurnitureRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FurnitureResponse'
          description: Furniture registered successfully
      summary: Register new furniture
      tags:
      - Furniture
  /furniture/personal_products:
    get:
      parameters:
      - example: 1
        explode: true
        in: query
        name: user_id
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FurnitureListResponse'
          description: Furniture list retrieved successfully
      summary: Get list of Personal furniture by user_id
      tags:
      - Furniture
  /furniture/{furniture_id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: furniture_id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          description: Furniture deleted successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Delete furniture
      tags:
      - Furniture
    get:
      parameters:
      - example: 1
        explode: false
        in: path
        name: furniture_id
        required: true
        schema:
          type: integer
        style: simple
      - example: 2
        explode: true
        in: query
        name: user_id
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FurnitureResponse'
          description: Furniture details retrieved successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Get furniture details
      tags:
      - Furniture
  /furniture/describe:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FurnitureDescribeRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FurnitureDescribeResponse'
          description: Furniture described successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Generate furniture description
      tags:
      - Furniture
  /furniture/recommend:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FurnitureRecommendRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FurnitureRecommendResponse'
          description: Furniture recommended successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Recommend furniture
      tags:
      - Furniture
  /trades:
    get:
      parameters:
      - explode: true
        in: query
        name: user_id
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeListResponse'
          description: Trade list retrieved successfully
      summary: Get list of trades history
      tags:
      - Trade
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestTradeRequest'
        required: true
      responses:
        "200":
          description: Trade requested successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Request a trade
      tags:
      - Trade
  /trades/{trade_id}:
    get:
      parameters:
      - explode: false
        in: path
        name: trade_id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeResponse'
          description: Trade details retrieved successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Get trade details
      tags:
      - Trade
    put:
      parameters:
      - explode: false
        in: path
        name: trade_id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateApprovalRequest'
        required: true
      responses:
        "200":
          description: Trade status updated successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Update approval status
      tags:
      - Trade
  /trades/{trade_id}/isChecked:
    put:
      parameters:
      - explode: false
        in: path
        name: trade_id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateIsCheckedRequest'
        required: true
      responses:
        "200":
          description: Trade status updated successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Update isChecked status
      tags:
      - Trade
  /favorite:
    delete:
      parameters:
      - explode: true
        in: query
        name: furniture_id
        required: true
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: user_id
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          description: Favorite deleted successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Delete favorite
      tags:
      - Favorite
    post:
      parameters:
      - explode: true
        in: query
        name: furniture_id
        required: true
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: user_id
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          description: Favorite added successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Add favorite
      tags:
      - Favorite
  /favorite/{furniture_id}/:
    get:
      parameters:
      - explode: false
        in: path
        name: furniture_id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FavoriteResponse'
          description: Favorite status retrieved successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Get favorite status
      tags:
      - Favorite
  /chat/{sender_id}/{receiver_id}:
    get:
      parameters:
      - explode: false
        in: path
        name: sender_id
        required: true
        schema:
          type: integer
        style: simple
      - explode: false
        in: path
        name: receiver_id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatListResponse'
          description: Chat list retrieved successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: validation error
      summary: Get chat list
      tags:
      - Chat
components:
  schemas:
    OKResponse:
      example:
        msg: msg
      properties:
        msg:
          title: msg
          type: string
      title: OKResponse
      type: object
    ErrorResponse:
      example:
        msg: msg
      properties:
        msg:
          title: msg
          type: string
      title: ErrorResponse
      type: object
    SignUpRequest:
      example:
        area: 0
        password: password
        username: username
      properties:
        username:
          title: username
          type: string
        password:
          title: password
          type: string
        area:
          title: area
          type: integer
      required:
      - area
      - password
      - username
      title: SignUpRequest
      type: object
    LoginRequest:
      example:
        password: password
        username: username
      properties:
        username:
          title: username
          type: string
        password:
          title: password
          type: string
      required:
      - password
      - username
      title: LoginRequest
      type: object
    LoginResponse:
      example:
        user_id: 0
      properties:
        user_id:
          title: user_id
          type: integer
      title: LoginResponse
      type: object
    RegisterFurnitureRequest:
      properties:
        user_id:
          example: 1
          type: integer
        product_name:
          example: 棚
          type: string
        image:
          format: binary
          type: string
        description:
          example: 新品未使用の白い棚です。
          type: string
        height:
          example: 100.0
          type: number
        width:
          example: 50.5
          type: number
        depth:
          example: 30
          type: number
        category:
          example: 5
          type: integer
        color:
          description: "色コード, URL(https://github.com/naka-c1024/Hack_U_Team1/blob/main/client/app/lib/constants.dart)"
          example: 0
          type: integer
        start_date:
          example: 2021-01-01
          format: date
          type: string
        end_date:
          example: 2024-01-01
          format: date
          type: string
        trade_place:
          example: 東京都渋谷区
          type: string
        condition:
          example: 0
          type: integer
      required:
      - category
      - color
      - condition
      - depth
      - description
      - height
      - image
      - product_name
      - trade_place
      - user_id
      - width
      type: object
    FurnitureListResponse:
      example:
        furniture:
        - area: 6
          end_date: 2024-01-01
          image: ""
          is_favorite: true
          color: 5
          description: description
          trade_place: trade_place
          product_name: product_name
          condition: 5
          size: 100 50 30
          is_sold: true
          furniture_id: 0
          category: 1
          username: ""
          start_date: 2021-01-01
        - area: 6
          end_date: 2024-01-01
          image: ""
          is_favorite: true
          color: 5
          description: description
          trade_place: trade_place
          product_name: product_name
          condition: 5
          size: 100 50 30
          is_sold: true
          furniture_id: 0
          category: 1
          username: ""
          start_date: 2021-01-01
      properties:
        furniture:
          items:
            $ref: '#/components/schemas/FurnitureResponse'
          title: furniture
          type: array
      title: FurnitureListResponse
      type: object
    FurnitureResponse:
      example:
        area: 6
        end_date: 2024-01-01
        image: ""
        is_favorite: true
        color: 5
        description: description
        trade_place: trade_place
        product_name: product_name
        condition: 5
        size: 100 50 30
        is_sold: true
        furniture_id: 0
        category: 1
        username: ""
        start_date: 2021-01-01
      properties:
        furniture_id:
          title: furniture_id
          type: integer
        image:
          format: binary
          title: image
          type: string
        area:
          description: "都道府県コード, URL(https://github.com/naka-c1024/Hack_U_Team1/blob/main/client/app/lib/constants.dart)"
          title: area
          type: integer
        username:
          format: binary
          title: username
          type: string
        product_name:
          title: product_name
          type: string
        description:
          title: description
          type: string
        size:
          description: height width depth(スペース区切り)
          example: 100 50 30
          title: size
          type: string
        category:
          description: "カテゴリコード, URL(https://github.com/naka-c1024/Hack_U_Team1/blob/main/client/app/lib/constants.dart)"
          title: category
          type: integer
        color:
          description: "色コード, URL(https://github.com/naka-c1024/Hack_U_Team1/blob/main/client/app/lib/constants.dart)"
          title: color
          type: integer
        condition:
          description: 6段階評価
          title: condition
          type: integer
        is_sold:
          title: is_sold
          type: boolean
        start_date:
          example: 2021-01-01
          format: date
          title: start_date
          type: string
        end_date:
          example: 2024-01-01
          format: date
          title: end_date
          type: string
        trade_place:
          description: 具体的な取引場所
          title: trade_place
          type: string
        is_favorite:
          description: 「いいねした商品」用
          title: is_favorite
          type: boolean
      title: FurnitureResponse
      type: object
    FurnitureDescribeRequest:
      properties:
        image:
          format: binary
          type: string
      required:
      - image
      type: object
    FurnitureDescribeResponse:
      example:
        color: 6
        description: description
        category: 0
        product_name: product_name
      properties:
        product_name:
          title: product_name
          type: string
        description:
          title: description
          type: string
        category:
          description: カテゴリコード(https://github.com/naka-c1024/Pasha-niture/blob/main/client/app/lib/Domain/constants.dart)
          title: category
          type: integer
        color:
          description: 色コード(https://github.com/naka-c1024/Pasha-niture/blob/main/client/app/lib/Domain/constants.dart)
          title: color
          type: integer
      title: FurnitureDescribeResponse
      type: object
    FurnitureRecommendRequest:
      properties:
        room_photo:
          format: binary
          type: string
        category:
          description: カテゴリコード(https://github.com/naka-c1024/Pasha-niture/blob/main/client/app/lib/Domain/constants.dart)
          type: integer
      required:
      - category
      - room_photo
      type: object
    FurnitureRecommendResponse:
      example:
        reason: reason
        furniture_list:
        - area: 6
          end_date: 2024-01-01
          image: ""
          is_favorite: true
          color: 5
          description: description
          trade_place: trade_place
          product_name: product_name
          condition: 5
          size: 100 50 30
          is_sold: true
          furniture_id: 0
          category: 1
          username: ""
          start_date: 2021-01-01
        - area: 6
          end_date: 2024-01-01
          image: ""
          is_favorite: true
          color: 5
          description: description
          trade_place: trade_place
          product_name: product_name
          condition: 5
          size: 100 50 30
          is_sold: true
          furniture_id: 0
          category: 1
          username: ""
          start_date: 2021-01-01
        color: 0
      properties:
        color:
          description: 色コード(https://github.com/naka-c1024/Pasha-niture/blob/main/client/app/lib/Domain/constants.dart)
          title: color
          type: integer
        reason:
          title: reason
          type: string
        furniture_list:
          items:
            $ref: '#/components/schemas/FurnitureResponse'
          title: furniture_list
          type: array
      title: FurnitureRecommendResponse
      type: object
    RequestTradeRequest:
      example:
        trade_date_time: 2021-01-01T00:00:00+09:00
        user_id: 6
        furniture_id: 0
      properties:
        furniture_id:
          title: furniture_id
          type: integer
        user_id:
          title: user_id
          type: integer
        trade_date_time:
          description: "家具受取日時, 日付は日本標準時, ISO 8601形式"
          example: 2021-01-01T00:00:00+09:00
          format: date-time
          title: trade_date_time
          type: string
      required:
      - furniture_id
      - trade_date_time
      - user_id
      title: RequestTradeRequest
      type: object
    TradeResponse:
      example:
        image: ""
        trade_id: 0
        trade_date_time: 2021-01-01T00:00:00+09:00
        giver_approval: true
        receiver_id: 5
        receiver_approval: true
        receiver_name: receiver_name
        is_checked: true
        trade_place: trade_place
        furniture_id: 6
        product_name: product_name
        giver_id: 1
      properties:
        trade_id:
          title: trade_id
          type: integer
        image:
          format: binary
          title: image
          type: string
        receiver_name:
          title: receiver_name
          type: string
        product_name:
          title: product_name
          type: string
        trade_place:
          description: 具体的な取引場所
          title: trade_place
          type: string
        furniture_id:
          title: furniture_id
          type: integer
        giver_id:
          title: giver_id
          type: integer
        receiver_id:
          title: receiver_id
          type: integer
        is_checked:
          title: is_checked
          type: boolean
        giver_approval:
          title: giver_approval
          type: boolean
        receiver_approval:
          title: receiver_approval
          type: boolean
        trade_date_time:
          description: "家具受取日時, 日付は日本標準時, ISO 8601形式"
          example: 2021-01-01T00:00:00+09:00
          format: date-time
          title: trade_date_time
          type: string
      title: TradeResponse
      type: object
    TradeListResponse:
      example:
        trades:
        - image: ""
          trade_id: 0
          trade_date_time: 2021-01-01T00:00:00+09:00
          giver_approval: true
          receiver_id: 5
          receiver_approval: true
          receiver_name: receiver_name
          is_checked: true
          trade_place: trade_place
          furniture_id: 6
          product_name: product_name
          giver_id: 1
        - image: ""
          trade_id: 0
          trade_date_time: 2021-01-01T00:00:00+09:00
          giver_approval: true
          receiver_id: 5
          receiver_approval: true
          receiver_name: receiver_name
          is_checked: true
          trade_place: trade_place
          furniture_id: 6
          product_name: product_name
          giver_id: 1
      properties:
        trades:
          items:
            $ref: '#/components/schemas/TradeResponse'
          title: trades
          type: array
      title: TradeListResponse
      type: object
    UpdateApprovalRequest:
      example:
        is_giver: true
      properties:
        is_giver:
          title: is_giver
          type: boolean
      required:
      - is_giver
      title: UpdateApprovalRequest
      type: object
    UpdateIsCheckedRequest:
      example:
        is_checked: true
      properties:
        is_checked:
          title: is_checked
          type: boolean
      required:
      - is_checked
      title: UpdateIsCheckedRequest
      type: object
    FavoriteResponse:
      example:
        favorites_count: 0
      properties:
        favorites_count:
          title: favorites_count
          type: integer
      title: FavoriteResponse
      type: object
    ChatListResponse:
      example:
        chats:
        - receiver_id: 1
          message: message
          sender_id: 6
          send_date_time: 2021-01-01T00:00:00+09:00
          chat_id: 0
        - receiver_id: 1
          message: message
          sender_id: 6
          send_date_time: 2021-01-01T00:00:00+09:00
          chat_id: 0
      properties:
        chats:
          items:
            $ref: '#/components/schemas/ChatResponse'
          title: chats
          type: array
      title: ChatListResponse
      type: object
    ChatResponse:
      example:
        receiver_id: 1
        message: message
        sender_id: 6
        send_date_time: 2021-01-01T00:00:00+09:00
        chat_id: 0
      properties:
        chat_id:
          title: chat_id
          type: integer
        sender_id:
          title: sender_id
          type: integer
        receiver_id:
          title: receiver_id
          type: integer
        message:
          title: message
          type: string
        send_date_time:
          description: "メッセージ送信日時, 日付は日本標準時, ISO 8601形式"
          example: 2021-01-01T00:00:00+09:00
          format: date-time
          title: send_date_time
          type: string
      title: ChatResponse
      type: object
